### ISSUE TITLE
howto implement bootstrap?

### ISSUE THREAD

**Issue by ryuken** [nicolaslopezj/simple-react-form#11]
Hi i know this is made for material-ui.
I wanna use it with bootstrap, but can't figure out so fast how I must implement it.
Could you point me in a direction?

**Comment by nicolaslopezj** [comment]
Just register all the input types you need to use.

https://github.com/nicolaslopezj/simple-react-form/blob/master/docs/create-input-types.md

**Comment by nicolaslopezj** [comment]
You could help here
https://github.com/fermuch/simple-react-form-bootstrap
