### ISSUE TITLE
Could I use this for production?

### ISSUE THREAD

**Issue by thearabbit** [nicolaslopezj/simple-react-form#14]
Could I use this for production?

**Comment by nicolaslopezj** [comment]
I'm using it, but I recommend to always test this package in your app

**Comment by thearabbit** [comment]
Thanks for your reply.
Could you detail for docs?

**Comment by nicolaslopezj** [comment]
The docs are not ready yet. I recommend you to:

- Learn how to create input types: [docs/create-input-types.md](https://github.com/nicolaslopezj/simple-react-form/blob/master/docs/create-input-types.md).
- See all the available fields for the material ui package: [material-ui/src/fields](https://github.com/nicolaslopezj/simple-react-form/tree/master/material-ui/src/fields).
- See the examples: [example](https://github.com/nicolaslopezj/simple-react-form/tree/master/example).
