### ISSUE TITLE
How about press enter classic submit in form?

### ISSUE THREAD

**Issue by ivansglazunov** [nicolaslopezj/simple-react-form#15]
1. not implemented, planned?
2. manually, how?
3. implemented, how?

PS. Thank you for the package. I can do something to help with the documentation and examples?

**Comment by nicolaslopezj** [comment]
This could be a new feature...

If you want to help, you can make the documentation for the material-ui field types

**Comment by joadr** [comment]
It's not a material-ui thing... The problem is that simple-react-form is not actually using forms

**Comment by ivansglazunov** [comment]
@joadr yes, but it can be implemented without form (tracking focus and enter).

**Comment by fermuch** [comment]
why not just use a `<form>` as a container?
