### ISSUE TITLE
Doubts about registerType

### ISSUE THREAD

**Issue by fermuch** [nicolaslopezj/simple-react-form#18]
Hello! I love your work!

I'm making [some fields for bootstrap](https://github.com/fermuch/simple-react-form-bootstrap), and looking at the source code I found some things I don't quite understand about `registerType`.

On the file [types.jsx](https://github.com/nicolaslopezj/simple-react-form/blob/master/form/src/types.jsx) you create the function `registerType`, with several arguments, but I can't see where most of them are being used.

For example:
* what is `description` for?
* how should I use `optionsDefinition` and `optionsDescription`?
* is `defaultOptions` auto-populated from simpleschema's `defaultValue`?
* if my field can only accept an object with `lat` and `lng`, like {lat: 3, lng: -5}, how should I defined that with `allowedTypes`?

And another thing, I am trying to build everything without using simpleschemas, to be sure everything is compatible in a not-meteor environment, but I couldn't find _how_ to display errors in the form.

**Comment by nicolaslopezj** [comment]
Hi @fermuch, thanks for making a bootstrap implementation! That's great!

The options are old! now they are not used, I forgot to remove them.

To display error in the fields you can pass the as props to the ```Field``` component.

```js
<Field fieldName="myField" errorMessage="My error message"/>
```
