### ISSUE TITLE
Change <Field type="string" /> to <Field type={Component} />

### ISSUE THREAD

**Issue by rgnevashev** [nicolaslopezj/simple-react-form#21]
how does that grab you?

**Comment by nicolaslopezj** [comment]
I was thinking a way to make it more "react way" and I think this is perfect!

Will do.

**Comment by rgnevashev** [comment]
Perfect! Your package is amazing. best of all!
If we use both material-ui and bootstrap, we can avoid conflict field types. 
We could be even make own <Text /> component and used in conjunction with other..

**Comment by fermuch** [comment]
I also like this idea, but how would it work? How would you define a component using only the schema? And what's the "default"? Core fields as default?

**Comment by nicolaslopezj** [comment]
It's ready.

@fermuch the old way to define fields is still working, but the other is the recommended.

To use default fields (like ```Checkbox``` for ```Boolean```) in the old way you should ```import simple-react-form-material-ui```.

In the new syntax there are no default fields, but you can pass the component in the SimpleSchema
