### ISSUE TITLE
Please add OnsenUI 2 set of fields and theme

### ISSUE THREAD

**Issue by cyclops24** [nicolaslopezj/simple-react-form#23]
Hi @nicolaslopezj,

First thanks for your awesome package. I post this issue as a feature request man. :wink: 
Please add OnsenUI 2 (https://onsen.io/v2/) theme if you can. Then many developers can use your form generator in mobile applications.
OnsenUI 2 is one of the most strongest mobile UI framework that based on react.

Thanks man.

**Comment by fermuch** [comment]
It's actually fairly simple to build your own components for the form. Take a look at [the docs](https://github.com/nicolaslopezj/simple-react-form#custom-input-types) and the [material-ui](https://github.com/nicolaslopezj/simple-react-form-material-ui) components

**Comment by nicolaslopezj** [comment]
I'm going to close this because this repo focus only on the main library, not the fields.
As @fermuch said, it's very easy to create custom fields and you can still use this issue to ask any questions.
