### ISSUE TITLE
React js warning after save

### ISSUE THREAD

**Issue by rgnevashev** [nicolaslopezj/simple-react-form#24]
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Form component.

**Comment by nicolaslopezj** [comment]
Is this duplicate of #4?

**Comment by rgnevashev** [comment]
yep. i have got same error. ver 1.6.10

**Comment by nicolaslopezj** [comment]
Ok, I'm going to check

**Comment by nicolaslopezj** [comment]
I think this issue is fixed, if you are still having this error it could be your app
