### ISSUE TITLE
Normal Validation

### ISSUE THREAD

**Issue by eliehamouche** [nicolaslopezj/simple-react-form#25]
Awesome package!
Just implemented it and worked great.

I'm not using autoform, just the plain implementation.

```
            <Form state={this.state}>
              <Field fieldName='name' label='Stack Name' type={Text}/>
              <Field fieldName='myArray' type={ArrayComponent}>
              First Field
              <Field fieldName='myField' type={Text}/>
              Second Field
              <Field fieldName='myField2' type={Text}/>
              </Field>
            </Form>
```

Is it possible to add validation from my SimpleSchema for when the form is submitted?
Is it also possible to add instant validation (onBlur) as well?

Thanks nicolasopezj!

**Comment by nicolaslopezj** [comment]
A automagical way to do that is not done yet 😞 but,

You can pass the the prop errorMessage to each field, so you can do the validation anyway you want. 
It's highly probable that the field you are using has a onBlur prop available. So you can fire the validation there.

**Comment by eliehamouche** [comment]
Sounds reasonable! I'm using material UI. I'll have a look.
Thanks nicolaslopezj!
