### ISSUE TITLE
[IDEA] add prop to clear form after submit

### ISSUE THREAD

**Issue by fermuch** [nicolaslopezj/simple-react-form#27]
Right now if I need to do a form clean, I have to manage the state locally, but since it's a common pattern to clean the form after success, I propose to add the prop `clearOnSuccess`.

I can do a PR, but I'd like to know if this is wanted by someone else before, and discuss if we should do it in a different way.

**Comment by fermuch** [comment]
This could be done with a method on the callbacks `on*`, but `this` is `undefined` in `onChange`, `onSuccess`, `onSubmit`.

**Comment by nicolaslopezj** [comment]
Great, I want this feature!

This would work for insert forms only right?

**Comment by fermuch** [comment]
I think this should work only in `function` and `insert`.
