### ISSUE TITLE
Create tests

### ISSUE THREAD

**Issue by nicolaslopezj** [nicolaslopezj/simple-react-form#29]
Help is needed to create the tests

Test that are needed:

- [x] Clean fields helper
- [x] Clean nulls helper
- [x] Doc to modifier helper
- [x] Replace index keys helper
- [x] Report nulls helper
- [x] ```onValueChange``` function on form
- [x] Automatic input generation
- [x] Form is rendered correctly
- [x] Object field is working correctly
- [x] Array field is working correctly (this has a history of troubles, test would be great here)

**Comment by fermuch** [comment]
Maybe a list of what tests are needed/wanted might help inspire some contributions?

**Comment by nicolaslopezj** [comment]
I've added a list
