### ISSUE TITLE
Creating a fieldtype for object doesn't save the new doc

### ISSUE THREAD

**Issue by joadr** [nicolaslopezj/simple-react-form#30]
I've been trying to add a fieldtype that will control an object in the schema and when submitting the form, it doesn't get saved and it's not for any validation issues (I've tried to add blackbox: true to the schema and still doesn't work.

Any help on this, is highly apreciated.

Thanks

**Comment by fermuch** [comment]
Hello! I suggest you installing [react-devtools](https://github.com/facebook/react-devtools) so you can inspect the state of the `Form`.

Can you provide some snippet of your field?

You get a prop "onChange", and you should use that to inform the Form your field changed. You can take a look of using `this.props.onChange` with an `Object` here: [geocoder](https://github.com/fermuch/simple-react-form-bootstrap/blob/master/src/extras/geocoder.js)

**Comment by joadr** [comment]
fermuch,
I've got react-devtools and I can see in chrome debugger that the onChange function is being called and with the right attribute.

Here's part of my schema
```javascript
...
'templates': {
    type: [Object],
    label: 'templates',
    optional: true,
    blackbox: true,
    srf: {
      type: ContractImages
    }
  },
  'templates.$.userId': {
    type: String,
    label: 'Firmante'
  },
  'templates.$.id': {
    type: String,
    label: 'Id',
    optional: true
  },
  'templates.$.page': {
    type: Number,
    label: 'Página',
    optional: true
  },
  'templates.$.type': {
    type: String,
    label: 'Tipo',
    optional: true
  },
  'templates.$.placeholder': {
    type: String,
    label: 'placeholder',
    optional: true
  },
  'templates.$.value': {
    type: String,
    label: 'valor',
    optional: true
  },
  'templates.$.date': {
    type: Date,
    label: 'fechaFirma',
    optional: true
  },
...
```

Then how i'm calling the component
```javascript
<Field
  fieldName='templates'
  contractImages={this.props.contract.contractImages}
  selectedUser={this.state.selectedUser}
  selectedType={this.state.selectedType}
/>
```

This is how I call onChange function on my field type ContractImages
```javascript
@autobind
updateRenders () {
  var renders = []
  _.each(this.state.rendersPerPage, function (page) {
    renders = _.union(renders, page.renders)
  })
  this.props.onChange(renders)
}
```

The console shows no errors (both client and server) and the collection doesn't see the changes...
The way to reproduce this is by creating a [Object] in the schema, then making a field type to control the changes.
I've talked with nicolaslopezj, and he told me the issue should be in this function but I've had trouble with the npm watch to use the local simple-react-form in my project.

https://github.com/nicolaslopezj/simple-react-form/blob/master/src/utility.js#L30

**Comment by fermuch** [comment]
Hmm. This seems very weird. Can you try _not_ using blackbox?

**Comment by joadr** [comment]
I've tried, I added blackbox because at first I taught it was a verification error, but it wasn't :(

**Comment by nicolaslopezj** [comment]
I think this error is that [this function](https://github.com/nicolaslopezj/simple-react-form/blob/master/src/utility.js#L30) is removing the fields.

I had the same problem and fixed it when I had a field type that was controlling an object. @joadr has a field type that is controlling an array

**Comment by fermuch** [comment]
@nicolaslopezj but controlling an array of objects should be possible.

**Comment by nicolaslopezj** [comment]
@fermuch totally, but there is a bug in that function that is filtering the fields that it shouldn't

**Comment by fermuch** [comment]
@joadr I can't reproduce the bug.

I cloned the repo [simple-react-forms-examples](https://github.com/nicolaslopezj/simple-react-form-examples) and added this to `imports/examples/simple-schema-crud/posts.jsx`

```jsx
import React from 'react';
import {FieldType} from 'simple-react-form';
class FoobarComp extends FieldType {
  constructor(props) {
    super(props);
    this.state = {
      value: props.value
    };
  }

  onChange(event) {
    this.setState({ value: event.target.value });
    this.props.onChange([{
      label: event.target.value,
      value: event.target.value
    }]);
  }

  render() {
    return (
      <input
        onChange={this.onChange.bind(this)}
        value={this.state.value || ''}
      />
    )
  }
}
```


And finally, in the same file, modified the schema with:

```
  foobar: {
    type: [Object],
    srf: {
      type: FoobarComp
    }
  },
  'foobar.$.label': {
    type: String
  },
  'foobar.$.value': {
    type: String
  }
```


This is a really dummy field, but it returns an array with an object.
The database stored the field correctly:
```
{
  "_id": "NCPrKPFrn5mkfn42u",
  "body": "asdasdasdasdasd",
  "title": "asdasdadasd",
  "foobar": [
    {
      "label": "this is just a test",
      "value": "this is just a test"
    }
  ],
  "authors": [
    {
      "name": "asdasd",
      "age": 123
    }
  ],
  "editor": {
    "name": "asdasd",
    "age": 44222
  }
}
```

Here you can see `foobar` has an array with an object inside, just as expected. I can even update the content with that field.

---


@joadr  Can you provide us a demo with the error? Or the full field you're creating?

**Comment by fermuch** [comment]
I pushed a demo here: https://github.com/fermuch/simple-react-form-examples/tree/simple-react-form-issue-30

Hope you can use that as a base, @joadr, or point me where it differs with yours.

**Comment by nicolaslopezj** [comment]
I've created test for the function that I thought was the problem and it seems that the problem is not there

**Comment by joadr** [comment]
I found the issue, I was giving the type in the schema, and it was a React.Component instead of FieldType, a warning should appear in this cases, but It didn't give any error. I'm so sorry and grateful at the same time for your effors :smile:

**Comment by JulianKingman** [comment]
I was about to reply to this post when I realized I had used `autoValue` instead of `defaultValue` in my SimpleSchema
😥
