### ISSUE TITLE
[String] array field

### ISSUE THREAD

**Issue by JulianKingman** [nicolaslopezj/simple-react-form#41]
I have a field defined in the schema as [String], and a field definition like so:

````javascript
"photos": {type: [String], optional: true, srf: {type: PhotoInput}},
````
But that showed just the PhotoInput, not in array form. So I thought, let's try this:

````javascript
"photos": {type: Array, optional: true, srf: {type: ArrayField}},
"photos.$": {type: String, srf: {type: PhotoInput}},
````
But that shows an empty array field, that is an array with no input field.

Does the array field only work for arrays of objects?

**Comment by nicolaslopezj** [comment]
```ArrayField``` is for arrays of object. You should create a field type for "photos".

I recommend you this examples:

- [Material UI File input (with multiple files support)](https://github.com/nicolaslopezj/simple-react-form-material-ui/blob/master/src/file/index.jsx).
- [Material UI Tags input (a string array field)](https://github.com/nicolaslopezj/simple-react-form-material-ui/blob/master/src/tags.jsx).

**Comment by JulianKingman** [comment]
Brilliant, thanks for the awesome support.
