### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by nicolaslopezj** [nicolaslopezj/simple-react-form#44]
We need help to make the documentation easier to read. Please make suggestions of changes to make it better

**Comment by fermuch** [comment]
The examples need meteor to run, so that might be a problem for some people. Why don't we add some jsfiddle demos?

Also, making an `API.md` listing all the props of the Form would be useful too, since having to read the source when you just stumbled across the project is a huge no.

**Comment by nicolaslopezj** [comment]
Great ideas @fermuch
