### ISSUE TITLE
Compatibility with node-simple-schema

### ISSUE THREAD

**Issue by ojread** [nicolaslopezj/simple-react-form#51]
While I can see the examples use the Meteor package aldeed:simple-schema, this is being replaced with the NPM package node-simple-schema.

There are some changes which appear to be breaking this package:
https://github.com/aldeed/meteor-simple-schema/blob/v2/CHANGELOG.md#200

Form validation is failing with:
`Uncaught TypeError: context.invalidKeys is not a function`

Are there plans to support this new version of simple-schema or shall I fork and attempt to make the required changes? It may be as simple as checking for the renamed functions.

Thanks for the great package!

**Comment by MentalGear** [comment]
Yes, it would be great to have compatibility with the latest simple schema validation version !

**Comment by prinzdezibel** [comment]
See: https://github.com/nicolaslopezj/simple-react-form/pull/62
