### ISSUE TITLE
Enhancement: Field should have an omit prop

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [nicolaslopezj/simple-react-form#52]
Use case: Field(Select) is wrapped or passed to ListContainer which renders it passing in needed props(options). However, ListContainer also passed in other props that are not needed. ListContainer is a library component thus without creating a intermediary wrapper component or a custom field React will throw the Unknown Props error.

**Comment by nicolaslopezj** [comment]
Can you should the example code?

**Comment by MichaelLeeHobbs** [comment]
Example:

    <ListContainer collection={feedbackTypes.collection}
                   publication="feedbackTypes"
                   resultsPropName="options">
      <Field fieldName='areaOfFeedback'
                 label='Type of Feedback'
                 type={Select}
                 omit={["currentUser", "ready", "count", "hasMore", "loadMore"]}/>
    </ListContainer>

**Comment by nicolaslopezj** [comment]
So this issue would be in this repo https://github.com/nicolaslopezj/simple-react-form-material-ui? to edit the select field

**Comment by MichaelLeeHobbs** [comment]
I'm not 100% sure I haven't dug too much into the source of either. The net result was that the props were passed all the way through to a div inside the Select from the material-ui.

**Comment by nicolaslopezj** [comment]
You should filter the results in the ```ListContainer```, because that component is providing the results

**Comment by MichaelLeeHobbs** [comment]
Like I said, dont have control over the ListContainer. I ended up make a intermediary component that goes between ListContainer and what ever components need data feed into them. I think I'm going to end up forking it when I have time or ask for control as it seems to have been abandoned.
