### ISSUE TITLE
Performance with lots of inputs

### ISSUE THREAD

**Issue by andrewvmail** [nicolaslopezj/simple-react-form#54]
Hello,

Made a form with 50 inputs some as complex array and such and I can see latency when I write inside the inputs/ On the computer it becomes slow and on mobile really slow, any ideas on how to speed things up?

Cheers for a great component

Thanks

**Comment by fermuch** [comment]
For those kind of forms with lots of inputs, I usually edit the fields' `onChange` with [lodash'](https://lodash.com/docs/4.17.4#debounce) `_.debounce` so they get called only once.

**Comment by andrewvmail** [comment]
@fermuch gotcha thanks!!

**Comment by andrewvmail** [comment]
@fermuch do i just put an onChange as a prop to Field?

**Comment by fermuch** [comment]
I use custom fields, so I edit those fields. For example, if you are using `simple-react-form-material-ui`'s Text field, edit this line: https://github.com/nicolaslopezj/simple-react-form-material-ui/blob/master/src/text.jsx#L38-L40 so `this.props.onChange` is only called once.

On the constructor, you can add:

```
constructor (props) {
  super(props)
  this.state = { value: props.value }

  // this line was added
  this.onChangeDebounced = _.debounce(props.onChange, 250); // debounce to 250ms
}
```

And on the onChange function:

```
onChange (event) {
  this.setState({ value: event.target.value })
  if (this.props.changeOnKeyDown) {
    // this line changed
    this.onChangeDebounced(event.target.value)
  }
}
```

**Comment by andrewvmail** [comment]
Thanks @fermuch

**Comment by nicolaslopezj** [comment]
Performance should be improved in v2
