### ISSUE TITLE
Sharing Custom Field Componets

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [nicolaslopezj/simple-react-form#56]
I've build a couple now that I would not mind sharing. One to is a Google Recaptcha that prevents the form from being submitted until the recaptcha has been passed and returns the recaptcha string for server side validation. The other is a drop zone that will upload a file using a callback, preview images, has a progress bar, and returns the url passed back to it from the uploader. Neither of these are specific to bootstrap or material, although I have only tested them with material.

**Comment by nicolaslopezj** [comment]
Awesome!

I would recommend you to create one repository for each one. I you need help, just ask
