### ISSUE TITLE
Add support to latest Simple Schema

### ISSUE THREAD

**Issue by brendonlamb** [nicolaslopezj/simple-react-form#58]
https://github.com/nicolaslopezj/simple-react-form/blob/master/src/utility/doc-to-modifier.js
https://github.com/nicolaslopezj/simple-react-form/blob/master/src/utility/doc-to-modifier.test.js

// FIXME
// This test throws an error since it depends on MongoObject, and
// MongoObject is a global that comes from aldeed:simple-schema.
// Since it's a meteor package, it can't be tested without
// meteor, so for now we have to skip this test.

Banging my head against this until I spotted the test file explaining things... I've been trying to use NPM packages over meteor packages... it seems however aldeed:simple-schema is an absolute dependency here (specifically, the MongoObject global it provides)

@nicolaslopezj Can you see about upgrading simple-react-form to support the new collection2 meteor package:
https://github.com/aldeed/meteor-collection2
and it's dependency (npm package) "simpl-schema":
https://github.com/aldeed/node-simple-schema

> Verify that aldeed:simple-schema is not listed in your .meteor/.versions file. If it is, you likely depend on some other package that has an explicit dependency on the Meteor aldeed:simple-schema package. This could cause problems or unexpected behavior. Work with that package author to get an updated version that does not explicitly depend on the aldeed:simple-schema package.

Don't mean to sound needy just trying to use the latest stuffs :D

**Comment by nicolaslopezj** [comment]
Lets keep one issue open (#51)
