### ISSUE TITLE
Pre-submit hook

### ISSUE THREAD

**Issue by Kolyasya** [nicolaslopezj/simple-react-form#60]
Hello, thank you for your package.
As I see it's API doesn't have any hooks (I use it with meteor Simple Schema package).
Do you have any plans for it? Or maybe you can advice how to preprocess form data, before sending it do DB.

**Comment by MichaelLeeHobbs** [comment]
Check out: https://github.com/aldeed/meteor-simple-schema#autovalue

If that doesn't handle your use case then give some more details.

**Comment by nicolaslopezj** [comment]
@Kolyasya it depends on how you are using the package. Can you post a piece of code?

**Comment by Kolyasya** [comment]
@MichaelLeeHobbs, @nicolaslopezj thank you for your answers. I'll post more information soon, as I'll come back to this project part
