### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by brendonlamb** [nicolaslopezj/simple-react-form#61]
How you accomplish validation error messaging per field when using simple schema? Is it possible and not documented?

I'd love to do something like this in my schema: 
`
        firstname: {
            type: String,
            optional: false,
            srf: {
                type: TextFieldComponent,
                errorText: (fieldInvalid) ? "ERROR" : "",
            },
            regEx: /.{1,}/
        },
`
But i'm not sure how to make it reactive (the fieldInvalid variable):

I've also tried handling it on the other end- before the "submit" - I can grab the collection schema and use it to validate each field... trouble is i'm not sure how to update the field "errorText" property using a ref to the form, is that even possible?

**Comment by nicolaslopezj** [comment]
Just pass the ```errorMessage``` as a prop in the field or ```errorMessages``` in the ```Form```
