### ISSUE TITLE
Wrong Mongo modifier format for update form with commitOnlyChanges={true}

### ISSUE THREAD

**Issue by Kshatra** [nicolaslopezj/simple-react-form#70]
```javascript
<Form
	schema={Schemas.UserUpdateSchema}
	type='function'
	ref={form => formRef = form}
	doc={userDoc}
	onSubmit={onSubmitAction}
	commitOnlyChanges={true}
>
	<Field fieldName='profile.firstName' type={Text}/>
</Form>

function onSubmitAction(changed) {...}
```

**changed** is expected to be: {'profile.firstName': someNewValue}
but the format is: {profile: {firstName: someNewValue}}
Such format does not allow to perform partial Mongo update because the whole profile is replaced instead of just 'firstName'.

Suppose the first variant should be the default behavier when SimpleSchema is not involved, but when it is, Meteor/Mongo is expected.

**Comment by nicolaslopezj** [comment]
Sorry, no longer Mongo integration
