### ISSUE TITLE
Uncaught Error: There is no field "Sections.0.0.SectionName" in the schema.

### ISSUE THREAD

**Issue by krishnapsms** [nicolaslopezj/simple-react-form#72]
i got the above error please help me further, I've simply added section object in to simple schema by following notation 
`Sections: {
    type: [Section],
    srf: {
      type: ArrayComponent
    }
  }`

**Comment by krishnapsms** [comment]
can i get the latest resource for this example - [simple-react-form.nicolaslopez.co - example](http://simple-react-form.nicolaslopez.co/)

**Comment by nicolaslopezj** [comment]
Schemas are no longer supported
