### ISSUE TITLE
Validation Issue

### ISSUE THREAD

**Issue by rgnevashev** [nicolaslopezj/simple-react-form#73]
```<Form state={docWithId}  type="function">```

![2017-06-08_19-25-20](https://user-images.githubusercontent.com/123600/26939585-6c4bd0e4-4c80-11e7-9fb7-0787dc896d3c.png)

**Comment by fermuch** [comment]
Can you please add the full <Form> with its childs?

**Comment by rgnevashev** [comment]
``` 
const doc = {_id: 1, name: 'test'}
<Form state={doc} collection={TestCollection} type="function" onSubmit={doc => console.log(doc)}>
 <Field fieldName="name" type={TextField} />
<button type="submit>Submit</button>
</Form>
```

**Comment by rgnevashev** [comment]
here https://github.com/nicolaslopezj/simple-react-form/blob/master/src/Form/index.js#L338
