### ISSUE TITLE
Remove Depend React Native

### ISSUE THREAD

**Issue by rgnevashev** [nicolaslopezj/simple-react-form#74]
![2017-06-18_14-34-59](https://user-images.githubusercontent.com/123600/27260380-644e80d4-5433-11e7-8251-bd6086cf936b.png)

**Comment by stilllife00** [comment]
Same problem here 

./~/simple-react-form/lib/Array/ArrayContextItem.js
Module not found: Can't resolve 'react-native' in '/Users/mirko/Sites/dxt-uploader/node_modules/simple-react-form/lib/Array'

Can you please make a PR ?

**Comment by nicolaslopezj** [comment]
Fixed in v2
